
allow-lan: false
mode: rule
log-level: debug
external-controller: '0.0.0.0:9091'
secret: 'aaaaab'

inbounds:
  - name: main-in
    type: socks
    listen: 127.0.0.1
    port: 1111
#    users:
#      - username: admin
#        password: admin

  - name: v2ray-in
    type: http
    listen: 127.0.0.1
    port: 2222
    users:
      - username: admin
        password: admin

  - name: forward-server
    type: direct
    listen: 127.0.0.1
    port: 3333
    redirect-addr: 185.199.110.153:80

proxies:
  - name: "luminati-一个很长的名字-123456789012345678901234567890"
    type: http
    server: zproxy.lum-superproxy.io
    port: 22225
    username: lum-customer-hl_29e0ce58-zone-data_center
    password: 6odvixy79hv7
    proxy-mode: auto

  - name: "http1"
    type: ssh
    server: 127.0.0.1
    port: 9111

  - name: "http2"
    type: http
    server: 127.0.0.1
    port: 9222
    username: "222"
    password: "222"
  - name: "luminati-一个很长的名字-123456789012345678901234567890luminati-一个很长的名字-123456789012345678901234567890"
    type: http
    server: zproxy.lum-superproxy.io
    port: 22225
    username: lum-customer-hl_29e0ce58-zone-data_center
    password: 6odvixy79hv7
    proxy-mode: auto

  - name: "v2ray-out"
    type: ssh
    server: 127.0.0.1
    port: 9111

  - name: "gost-1"
    type: ssh
    server: 127.0.0.1
    port: 9111

proxy-groups:

  - name: gost-proxy-chain
    type: relay
    proxies:
      - http1
      - http2

rules:
  - Inbound,main-in,v2ray-out
  - Inbound,v2ray-in,gost-proxy-chain
  - Inbound,forward-server,gost-1
  - MATCH,v2ray-out
  - MATCH,http2
