
allow-lan: false
mode: rule
log-level: debug
external-controller: '0.0.0.0:9091'
secret: 'aaaaab'

inbounds:
  - name: main-in
    type: socks
    listen: 127.0.0.1
    port: 1111  

proxies:
  - name: "socks1"
    type: socks5
    server: 127.0.0.1
    port: 7777  

  - name: "socks2"
    type: socks5
    server: 127.0.0.1
    port: 7778
  

  - name: "ssh1"
    type: ssh
    server: 127.0.0.1
    port: 7779

  - name: "ssh2"
    type: ssh
    server: 127.0.0.1
    port: 7800  

proxy-groups:

  - name: relay
    type: relay
    proxies:
      # - socks1
      - ssh1
      - ssh2
      - socks2

rules: 
  - MATCH,relay
